### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by schotime** [jeroenverfallie/atom-cerebral-signal-bootstrap#1]
[Enter steps to reproduce below:]
1. ...Create function in signals file
2. ...Right click on it and invoke atom module

**Atom Version**: 1.7.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-cerebral-signal-bootstrap](https://github.com/jeroenverfallie/atom-cerebral-signal-bootstrap) package, v0.10.0
### Stack Trace

Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

```
At /C:/Users/Adam/.atom/packages/atom-cerebral-signal-bootstrap/lib/parser.js:123

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at parseCollection (C:/Users/Adam/.atom/packages/atom-cerebral-signal-bootstrap/lib/parser.js:106:27)
    at C:/Users/Adam/.atom/packages/atom-cerebral-signal-bootstrap/lib/parser.js:117:82
    at Array.reduce (native)
    at parseCollection (C:/Users/Adam/.atom/packages/atom-cerebral-signal-bootstrap/lib/parser.js:117:49)
    at C:/Users/Adam/.atom/packages/atom-cerebral-signal-bootstrap/lib/parser.js:117:82
    at Array.reduce (native)
    at parseCollection (C:/Users/Adam/.atom/packages/atom-cerebral-signal-bootstrap/lib/parser.js:117:49)
    at getDeclaration (C:/Users/Adam/.atom/packages/atom-cerebral-signal-bootstrap/lib/parser.js:65:23)
    at Object.parse (C:/Users/Adam/.atom/packages/atom-cerebral-signal-bootstrap/lib/parser.js:12:25)
    at SignalBootstrap.execute (C:/Users/Adam/.atom/packages/atom-cerebral-signal-bootstrap/lib/SignalBootstrap.js:101:36)
    at atom-workspace.atomCerebralSignalBootstrapExecute (C:/Users/Adam/.atom/packages/atom-cerebral-signal-bootstrap/lib/SignalBootstrap.js:85:66)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Adam\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Adam\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Adam\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\Adam\AppData\Local\atom\app-1.7.2\resources\app.asar\src\atom-environment.js:1106:28)
    at EventEmitter.outerCallback (C:\Users\Adam\AppData\Local\atom\app-1.7.2\resources\app.asar\src\application-delegate.js:327:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```
### Commands

```
     -0:03.9.0 atom-cerebral-signal-bootstrap:execute (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "advanced-open-file",
      "atom-beautify"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-cerebral-signal-bootstrap, v0.10.0
atom-yeoman, v0.3.15
ctrl-last-tab, v0.3.0
json-schema, v0.1.15
language-javascript-jsx, v0.3.7
linter, v1.11.4
omnisharp-atom, v0.28.0

# Dev
No dev packages
```

**Comment by schotime** [comment]
Any news on the issue?

**Comment by jeroenverfallie** [comment]
@schotime It's on my list for today, should have it fixed by tonight

**Comment by schotime** [comment]
@jeroenverfallie awesome!

**Comment by jeroenverfallie** [comment]
@schotime  0.10.1 published, this fixes output paths being an identifier instead of array. This might be related to your issue.

If you're still facing problems after this, please provide a sample structure that fails 😄

**Comment by schotime** [comment]
Its alive!!! awesome. Works great.
